#############################
## 相机标定的参数
#############################
caliboard : # 标定板
  row : 7 # 行数
  column : 9 # 列数
  ceil_size : 20 # 格子的尺寸,单位mm
cali_img_source_path: 'data' # 标定图像的存储路径
cali_info_save_path : 'config/camera_info.bin' # 相机标定信息存储路径
