(cl:in-package segway_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          BATTERY_STATE_OF_CHARGE_PERCENT-VAL
          BATTERY_STATE_OF_CHARGE_PERCENT
          BATTERY_CURRENT_A0PK-VAL
          BATTERY_CURRENT_A0PK
          BATTERY_VOLTAGE_V-VAL
          BATTERY_VOLTAGE_V
          MAX_CELL_TEMP_DEGC-VAL
          MAX_CELL_TEMP_DEGC
          MAX_PCBA_TEMP_DEGC-VAL
          MAX_PCBA_TEMP_DEGC
          MAX_CELL_VOLTAGE_V-VAL
          MAX_CELL_VOLTAGE_V
          MIN_CELL_VOLTAGE_V-VAL
          MIN_CELL_VOLTAGE_V
          BATTERY_INTERFACE_STATUS_BITS-VAL
          BATTERY_INTERFACE_STATUS_BITS
))