// Generated by gencpp from file bwi_msgs/LEDControlFeedback.msg
// DO NOT EDIT!


#ifndef BWI_MSGS_MESSAGE_LEDCONTROLFEEDBACK_H
#define BWI_MSGS_MESSAGE_LEDCONTROLFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bwi_msgs
{
template <class ContainerAllocator>
struct LEDControlFeedback_
{
  typedef LEDControlFeedback_<ContainerAllocator> Type;

  LEDControlFeedback_()
    : time_running()  {
    }
  LEDControlFeedback_(const ContainerAllocator& _alloc)
    : time_running()  {
  (void)_alloc;
    }



   typedef ros::Duration _time_running_type;
  _time_running_type time_running;





  typedef boost::shared_ptr< ::bwi_msgs::LEDControlFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bwi_msgs::LEDControlFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct LEDControlFeedback_

typedef ::bwi_msgs::LEDControlFeedback_<std::allocator<void> > LEDControlFeedback;

typedef boost::shared_ptr< ::bwi_msgs::LEDControlFeedback > LEDControlFeedbackPtr;
typedef boost::shared_ptr< ::bwi_msgs::LEDControlFeedback const> LEDControlFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bwi_msgs::LEDControlFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bwi_msgs::LEDControlFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bwi_msgs::LEDControlFeedback_<ContainerAllocator1> & lhs, const ::bwi_msgs::LEDControlFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.time_running == rhs.time_running;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bwi_msgs::LEDControlFeedback_<ContainerAllocator1> & lhs, const ::bwi_msgs::LEDControlFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bwi_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::bwi_msgs::LEDControlFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bwi_msgs::LEDControlFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_msgs::LEDControlFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_msgs::LEDControlFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_msgs::LEDControlFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_msgs::LEDControlFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bwi_msgs::LEDControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75824f08f05571689ccf412bca8194f3";
  }

  static const char* value(const ::bwi_msgs::LEDControlFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75824f08f0557168ULL;
  static const uint64_t static_value2 = 0x9ccf412bca8194f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::bwi_msgs::LEDControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bwi_msgs/LEDControlFeedback";
  }

  static const char* value(const ::bwi_msgs::LEDControlFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bwi_msgs::LEDControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"duration time_running\n"
;
  }

  static const char* value(const ::bwi_msgs::LEDControlFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bwi_msgs::LEDControlFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_running);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LEDControlFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bwi_msgs::LEDControlFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bwi_msgs::LEDControlFeedback_<ContainerAllocator>& v)
  {
    s << indent << "time_running: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.time_running);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BWI_MSGS_MESSAGE_LEDCONTROLFEEDBACK_H
