// Generated by gencpp from file bwi_msgs/QuestionDialogRequest.msg
// DO NOT EDIT!


#ifndef BWI_MSGS_MESSAGE_QUESTIONDIALOGREQUEST_H
#define BWI_MSGS_MESSAGE_QUESTIONDIALOGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bwi_msgs
{
template <class ContainerAllocator>
struct QuestionDialogRequest_
{
  typedef QuestionDialogRequest_<ContainerAllocator> Type;

  QuestionDialogRequest_()
    : type(0)
    , message()
    , options()
    , timeout(0.0)  {
    }
  QuestionDialogRequest_(const ContainerAllocator& _alloc)
    : type(0)
    , message(_alloc)
    , options(_alloc)
    , timeout(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _options_type;
  _options_type options;

   typedef float _timeout_type;
  _timeout_type timeout;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(DISPLAY)
  #undef DISPLAY
#endif
#if defined(_WIN32) && defined(CHOICE_QUESTION)
  #undef CHOICE_QUESTION
#endif
#if defined(_WIN32) && defined(TEXT_QUESTION)
  #undef TEXT_QUESTION
#endif
#if defined(_WIN32) && defined(NO_TIMEOUT)
  #undef NO_TIMEOUT
#endif
#if defined(_WIN32) && defined(NO_RESPONSE)
  #undef NO_RESPONSE
#endif
#if defined(_WIN32) && defined(TIMED_OUT)
  #undef TIMED_OUT
#endif
#if defined(_WIN32) && defined(TEXT_RESPONSE)
  #undef TEXT_RESPONSE
#endif
#if defined(_WIN32) && defined(PREEMPTED)
  #undef PREEMPTED
#endif

  enum {
    DISPLAY = 0,
    CHOICE_QUESTION = 1,
    TEXT_QUESTION = 2,
    NO_RESPONSE = -1,
    TIMED_OUT = -2,
    TEXT_RESPONSE = -3,
    PREEMPTED = -4,
  };

  static const float NO_TIMEOUT;

  typedef boost::shared_ptr< ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator> const> ConstPtr;

}; // struct QuestionDialogRequest_

typedef ::bwi_msgs::QuestionDialogRequest_<std::allocator<void> > QuestionDialogRequest;

typedef boost::shared_ptr< ::bwi_msgs::QuestionDialogRequest > QuestionDialogRequestPtr;
typedef boost::shared_ptr< ::bwi_msgs::QuestionDialogRequest const> QuestionDialogRequestConstPtr;

// constants requiring out of line definition

   

   

   

   
   template<typename ContainerAllocator> const float
      QuestionDialogRequest_<ContainerAllocator>::NO_TIMEOUT =
        
          0.0
        
        ;
   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator1> & lhs, const ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.message == rhs.message &&
    lhs.options == rhs.options &&
    lhs.timeout == rhs.timeout;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator1> & lhs, const ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bwi_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ce87aad338e077acf0196b16cf4ea7a";
  }

  static const char* value(const ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ce87aad338e077aULL;
  static const uint64_t static_value2 = 0xcf0196b16cf4ea7aULL;
};

template<class ContainerAllocator>
struct DataType< ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bwi_msgs/QuestionDialogRequest";
  }

  static const char* value(const ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Constants defining question type\n"
"int32 DISPLAY = 0\n"
"int32 CHOICE_QUESTION = 1\n"
"int32 TEXT_QUESTION = 2\n"
"\n"
"# Constants regarding timeout\n"
"float32 NO_TIMEOUT=0.0\n"
"\n"
"# Constants for response index\n"
"int32 NO_RESPONSE=-1\n"
"int32 TIMED_OUT=-2\n"
"int32 TEXT_RESPONSE=-3\n"
"int32 PREEMPTED=-4\n"
"\n"
"int32 type\n"
"string message\n"
"string[] options # used in choice questions\n"
"float32 timeout\n"
"\n"
;
  }

  static const char* value(const ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.message);
      stream.next(m.options);
      stream.next(m.timeout);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuestionDialogRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bwi_msgs::QuestionDialogRequest_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "options[]" << std::endl;
    for (size_t i = 0; i < v.options.size(); ++i)
    {
      s << indent << "  options[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.options[i]);
    }
    s << indent << "timeout: ";
    Printer<float>::stream(s, indent + "  ", v.timeout);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BWI_MSGS_MESSAGE_QUESTIONDIALOGREQUEST_H
