// Generated by gencpp from file bwi_msgs/SaveImageResponseResponse.msg
// DO NOT EDIT!


#ifndef BWI_MSGS_MESSAGE_SAVEIMAGERESPONSERESPONSE_H
#define BWI_MSGS_MESSAGE_SAVEIMAGERESPONSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bwi_msgs
{
template <class ContainerAllocator>
struct SaveImageResponseResponse_
{
  typedef SaveImageResponseResponse_<ContainerAllocator> Type;

  SaveImageResponseResponse_()
    : success(false)  {
    }
  SaveImageResponseResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SaveImageResponseResponse_

typedef ::bwi_msgs::SaveImageResponseResponse_<std::allocator<void> > SaveImageResponseResponse;

typedef boost::shared_ptr< ::bwi_msgs::SaveImageResponseResponse > SaveImageResponseResponsePtr;
typedef boost::shared_ptr< ::bwi_msgs::SaveImageResponseResponse const> SaveImageResponseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator1> & lhs, const ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator1> & lhs, const ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bwi_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bwi_msgs/SaveImageResponseResponse";
  }

  static const char* value(const ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveImageResponseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bwi_msgs::SaveImageResponseResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BWI_MSGS_MESSAGE_SAVEIMAGERESPONSERESPONSE_H
