// Generated by gencpp from file bwi_msgs/ScavHuntResponse.msg
// DO NOT EDIT!


#ifndef BWI_MSGS_MESSAGE_SCAVHUNTRESPONSE_H
#define BWI_MSGS_MESSAGE_SCAVHUNTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bwi_msgs
{
template <class ContainerAllocator>
struct ScavHuntResponse_
{
  typedef ScavHuntResponse_<ContainerAllocator> Type;

  ScavHuntResponse_()
    {
    }
  ScavHuntResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::bwi_msgs::ScavHuntResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bwi_msgs::ScavHuntResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ScavHuntResponse_

typedef ::bwi_msgs::ScavHuntResponse_<std::allocator<void> > ScavHuntResponse;

typedef boost::shared_ptr< ::bwi_msgs::ScavHuntResponse > ScavHuntResponsePtr;
typedef boost::shared_ptr< ::bwi_msgs::ScavHuntResponse const> ScavHuntResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bwi_msgs::ScavHuntResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bwi_msgs::ScavHuntResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace bwi_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::bwi_msgs::ScavHuntResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bwi_msgs::ScavHuntResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_msgs::ScavHuntResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_msgs::ScavHuntResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_msgs::ScavHuntResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_msgs::ScavHuntResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bwi_msgs::ScavHuntResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::bwi_msgs::ScavHuntResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::bwi_msgs::ScavHuntResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bwi_msgs/ScavHuntResponse";
  }

  static const char* value(const ::bwi_msgs::ScavHuntResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bwi_msgs::ScavHuntResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::bwi_msgs::ScavHuntResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bwi_msgs::ScavHuntResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ScavHuntResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bwi_msgs::ScavHuntResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::bwi_msgs::ScavHuntResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // BWI_MSGS_MESSAGE_SCAVHUNTRESPONSE_H
