// Generated by gencpp from file bwi_msgs/StopBaseRequest.msg
// DO NOT EDIT!


#ifndef BWI_MSGS_MESSAGE_STOPBASEREQUEST_H
#define BWI_MSGS_MESSAGE_STOPBASEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <bwi_msgs/StopBaseStatus.h>

namespace bwi_msgs
{
template <class ContainerAllocator>
struct StopBaseRequest_
{
  typedef StopBaseRequest_<ContainerAllocator> Type;

  StopBaseRequest_()
    : status()
    , requester()  {
    }
  StopBaseRequest_(const ContainerAllocator& _alloc)
    : status(_alloc)
    , requester(_alloc)  {
  (void)_alloc;
    }



   typedef  ::bwi_msgs::StopBaseStatus_<ContainerAllocator>  _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _requester_type;
  _requester_type requester;





  typedef boost::shared_ptr< ::bwi_msgs::StopBaseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bwi_msgs::StopBaseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StopBaseRequest_

typedef ::bwi_msgs::StopBaseRequest_<std::allocator<void> > StopBaseRequest;

typedef boost::shared_ptr< ::bwi_msgs::StopBaseRequest > StopBaseRequestPtr;
typedef boost::shared_ptr< ::bwi_msgs::StopBaseRequest const> StopBaseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bwi_msgs::StopBaseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bwi_msgs::StopBaseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bwi_msgs::StopBaseRequest_<ContainerAllocator1> & lhs, const ::bwi_msgs::StopBaseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.requester == rhs.requester;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bwi_msgs::StopBaseRequest_<ContainerAllocator1> & lhs, const ::bwi_msgs::StopBaseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bwi_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::bwi_msgs::StopBaseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bwi_msgs::StopBaseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_msgs::StopBaseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_msgs::StopBaseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_msgs::StopBaseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_msgs::StopBaseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bwi_msgs::StopBaseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "176fd38d0b8455650188bf167ac42bdc";
  }

  static const char* value(const ::bwi_msgs::StopBaseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x176fd38d0b845565ULL;
  static const uint64_t static_value2 = 0x0188bf167ac42bdcULL;
};

template<class ContainerAllocator>
struct DataType< ::bwi_msgs::StopBaseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bwi_msgs/StopBaseRequest";
  }

  static const char* value(const ::bwi_msgs::StopBaseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bwi_msgs::StopBaseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "### Stop base controller service call\n"
"#\n"
"#   Since there can be multiple requesters, the current status\n"
"#   returned in the response message may not immediately match the\n"
"#   original request.\n"
"#\n"
"#   If more than one requester sets a PAUSED status, the robot base\n"
"#   will remain motionless until they all request RUNNING again.  If\n"
"#   any requester sets STOPPED, no further requests will be met, the\n"
"#   status remaining permantently STOPPED.\n"
"#\n"
"#   The requester name should be sufficiently unique to avoid multiple\n"
"#   requesters picking the same string.  A reasonable choice is the\n"
"#   ROS node name.\n"
"\n"
"StopBaseStatus status   # new status requested\n"
"string requester        # self-assigned requester name\n"
"\n"
"================================================================================\n"
"MSG: bwi_msgs/StopBaseStatus\n"
"### Stop base controller status.\n"
"\n"
"uint8 status\n"
"\n"
"# Constants defining the possible states:\n"
"uint8 RUNNING = 0       # robot base running normally\n"
"uint8 PAUSED =  1       # robot base motion paused\n"
"uint8 STOPPED = 2       # terminal state: no more movement allowed\n"
;
  }

  static const char* value(const ::bwi_msgs::StopBaseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bwi_msgs::StopBaseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.requester);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopBaseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bwi_msgs::StopBaseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bwi_msgs::StopBaseRequest_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    s << std::endl;
    Printer< ::bwi_msgs::StopBaseStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
    s << indent << "requester: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.requester);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BWI_MSGS_MESSAGE_STOPBASEREQUEST_H
