// Generated by gencpp from file bwi_msgs/UpdateObjectRequest.msg
// DO NOT EDIT!


#ifndef BWI_MSGS_MESSAGE_UPDATEOBJECTREQUEST_H
#define BWI_MSGS_MESSAGE_UPDATEOBJECTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace bwi_msgs
{
template <class ContainerAllocator>
struct UpdateObjectRequest_
{
  typedef UpdateObjectRequest_<ContainerAllocator> Type;

  UpdateObjectRequest_()
    : object_name()
    , pose()
    , type(0)  {
    }
  UpdateObjectRequest_(const ContainerAllocator& _alloc)
    : object_name(_alloc)
    , pose(_alloc)
    , type(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _object_name_type;
  _object_name_type object_name;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef int32_t _type_type;
  _type_type type;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(UPDATE)
  #undef UPDATE
#endif
#if defined(_WIN32) && defined(REMOVE)
  #undef REMOVE
#endif

  enum {
    UPDATE = 0,
    REMOVE = 1,
  };


  typedef boost::shared_ptr< ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateObjectRequest_

typedef ::bwi_msgs::UpdateObjectRequest_<std::allocator<void> > UpdateObjectRequest;

typedef boost::shared_ptr< ::bwi_msgs::UpdateObjectRequest > UpdateObjectRequestPtr;
typedef boost::shared_ptr< ::bwi_msgs::UpdateObjectRequest const> UpdateObjectRequestConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator1> & lhs, const ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator2> & rhs)
{
  return lhs.object_name == rhs.object_name &&
    lhs.pose == rhs.pose &&
    lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator1> & lhs, const ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bwi_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a01e762758842bbdbfe17c1de4dd2ec6";
  }

  static const char* value(const ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa01e762758842bbdULL;
  static const uint64_t static_value2 = 0xbfe17c1de4dd2ec6ULL;
};

template<class ContainerAllocator>
struct DataType< ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bwi_msgs/UpdateObjectRequest";
  }

  static const char* value(const ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 UPDATE = 0\n"
"int32 REMOVE = 1\n"
"\n"
"string object_name\n"
"geometry_msgs/Pose pose\n"
"int32 type\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_name);
      stream.next(m.pose);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateObjectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bwi_msgs::UpdateObjectRequest_<ContainerAllocator>& v)
  {
    s << indent << "object_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.object_name);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BWI_MSGS_MESSAGE_UPDATEOBJECTREQUEST_H
