// Generated by gencpp from file plan_execution/AnswerSet.msg
// DO NOT EDIT!


#ifndef PLAN_EXECUTION_MESSAGE_ANSWERSET_H
#define PLAN_EXECUTION_MESSAGE_ANSWERSET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <plan_execution/AspFluent.h>

namespace plan_execution
{
template <class ContainerAllocator>
struct AnswerSet_
{
  typedef AnswerSet_<ContainerAllocator> Type;

  AnswerSet_()
    : fluents()
    , satisfied(false)  {
    }
  AnswerSet_(const ContainerAllocator& _alloc)
    : fluents(_alloc)
    , satisfied(false)  {
  (void)_alloc;
    }



   typedef std::vector< ::plan_execution::AspFluent_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::plan_execution::AspFluent_<ContainerAllocator> >> _fluents_type;
  _fluents_type fluents;

   typedef uint8_t _satisfied_type;
  _satisfied_type satisfied;





  typedef boost::shared_ptr< ::plan_execution::AnswerSet_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plan_execution::AnswerSet_<ContainerAllocator> const> ConstPtr;

}; // struct AnswerSet_

typedef ::plan_execution::AnswerSet_<std::allocator<void> > AnswerSet;

typedef boost::shared_ptr< ::plan_execution::AnswerSet > AnswerSetPtr;
typedef boost::shared_ptr< ::plan_execution::AnswerSet const> AnswerSetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plan_execution::AnswerSet_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plan_execution::AnswerSet_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::plan_execution::AnswerSet_<ContainerAllocator1> & lhs, const ::plan_execution::AnswerSet_<ContainerAllocator2> & rhs)
{
  return lhs.fluents == rhs.fluents &&
    lhs.satisfied == rhs.satisfied;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::plan_execution::AnswerSet_<ContainerAllocator1> & lhs, const ::plan_execution::AnswerSet_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace plan_execution

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::plan_execution::AnswerSet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plan_execution::AnswerSet_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plan_execution::AnswerSet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plan_execution::AnswerSet_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plan_execution::AnswerSet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plan_execution::AnswerSet_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plan_execution::AnswerSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b4c2ce462411c0af968d1312672b24e";
  }

  static const char* value(const ::plan_execution::AnswerSet_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b4c2ce462411c0aULL;
  static const uint64_t static_value2 = 0xf968d1312672b24eULL;
};

template<class ContainerAllocator>
struct DataType< ::plan_execution::AnswerSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plan_execution/AnswerSet";
  }

  static const char* value(const ::plan_execution::AnswerSet_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plan_execution::AnswerSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "AspFluent[] fluents\n"
"bool satisfied\n"
"\n"
"================================================================================\n"
"MSG: plan_execution/AspFluent\n"
"string name\n"
"string[] variables\n"
"uint32 timeStep\n"
;
  }

  static const char* value(const ::plan_execution::AnswerSet_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plan_execution::AnswerSet_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fluents);
      stream.next(m.satisfied);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AnswerSet_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plan_execution::AnswerSet_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plan_execution::AnswerSet_<ContainerAllocator>& v)
  {
    s << indent << "fluents[]" << std::endl;
    for (size_t i = 0; i < v.fluents.size(); ++i)
    {
      s << indent << "  fluents[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::plan_execution::AspFluent_<ContainerAllocator> >::stream(s, indent + "    ", v.fluents[i]);
    }
    s << indent << "satisfied: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.satisfied);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLAN_EXECUTION_MESSAGE_ANSWERSET_H
