// Generated by gencpp from file plan_execution/AspRule.msg
// DO NOT EDIT!


#ifndef PLAN_EXECUTION_MESSAGE_ASPRULE_H
#define PLAN_EXECUTION_MESSAGE_ASPRULE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <plan_execution/AspFluent.h>
#include <plan_execution/AspFluent.h>

namespace plan_execution
{
template <class ContainerAllocator>
struct AspRule_
{
  typedef AspRule_<ContainerAllocator> Type;

  AspRule_()
    : head()
    , body()  {
    }
  AspRule_(const ContainerAllocator& _alloc)
    : head(_alloc)
    , body(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::plan_execution::AspFluent_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::plan_execution::AspFluent_<ContainerAllocator> >> _head_type;
  _head_type head;

   typedef std::vector< ::plan_execution::AspFluent_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::plan_execution::AspFluent_<ContainerAllocator> >> _body_type;
  _body_type body;





  typedef boost::shared_ptr< ::plan_execution::AspRule_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plan_execution::AspRule_<ContainerAllocator> const> ConstPtr;

}; // struct AspRule_

typedef ::plan_execution::AspRule_<std::allocator<void> > AspRule;

typedef boost::shared_ptr< ::plan_execution::AspRule > AspRulePtr;
typedef boost::shared_ptr< ::plan_execution::AspRule const> AspRuleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plan_execution::AspRule_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plan_execution::AspRule_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::plan_execution::AspRule_<ContainerAllocator1> & lhs, const ::plan_execution::AspRule_<ContainerAllocator2> & rhs)
{
  return lhs.head == rhs.head &&
    lhs.body == rhs.body;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::plan_execution::AspRule_<ContainerAllocator1> & lhs, const ::plan_execution::AspRule_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace plan_execution

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::plan_execution::AspRule_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plan_execution::AspRule_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plan_execution::AspRule_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plan_execution::AspRule_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plan_execution::AspRule_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plan_execution::AspRule_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plan_execution::AspRule_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58135dc904c6164beb7b31dfd47be280";
  }

  static const char* value(const ::plan_execution::AspRule_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58135dc904c6164bULL;
  static const uint64_t static_value2 = 0xeb7b31dfd47be280ULL;
};

template<class ContainerAllocator>
struct DataType< ::plan_execution::AspRule_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plan_execution/AspRule";
  }

  static const char* value(const ::plan_execution::AspRule_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plan_execution::AspRule_<ContainerAllocator> >
{
  static const char* value()
  {
    return "AspFluent[] head\n"
"AspFluent[] body\n"
"\n"
"================================================================================\n"
"MSG: plan_execution/AspFluent\n"
"string name\n"
"string[] variables\n"
"uint32 timeStep\n"
;
  }

  static const char* value(const ::plan_execution::AspRule_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plan_execution::AspRule_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.head);
      stream.next(m.body);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AspRule_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plan_execution::AspRule_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plan_execution::AspRule_<ContainerAllocator>& v)
  {
    s << indent << "head[]" << std::endl;
    for (size_t i = 0; i < v.head.size(); ++i)
    {
      s << indent << "  head[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::plan_execution::AspFluent_<ContainerAllocator> >::stream(s, indent + "    ", v.head[i]);
    }
    s << indent << "body[]" << std::endl;
    for (size_t i = 0; i < v.body.size(); ++i)
    {
      s << indent << "  body[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::plan_execution::AspFluent_<ContainerAllocator> >::stream(s, indent + "    ", v.body[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLAN_EXECUTION_MESSAGE_ASPRULE_H
