// Generated by gencpp from file plan_execution/ComputePlanRequest.msg
// DO NOT EDIT!


#ifndef PLAN_EXECUTION_MESSAGE_COMPUTEPLANREQUEST_H
#define PLAN_EXECUTION_MESSAGE_COMPUTEPLANREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <plan_execution/AspRule.h>

namespace plan_execution
{
template <class ContainerAllocator>
struct ComputePlanRequest_
{
  typedef ComputePlanRequest_<ContainerAllocator> Type;

  ComputePlanRequest_()
    : goal()  {
    }
  ComputePlanRequest_(const ContainerAllocator& _alloc)
    : goal(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::plan_execution::AspRule_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::plan_execution::AspRule_<ContainerAllocator> >> _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::plan_execution::ComputePlanRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plan_execution::ComputePlanRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ComputePlanRequest_

typedef ::plan_execution::ComputePlanRequest_<std::allocator<void> > ComputePlanRequest;

typedef boost::shared_ptr< ::plan_execution::ComputePlanRequest > ComputePlanRequestPtr;
typedef boost::shared_ptr< ::plan_execution::ComputePlanRequest const> ComputePlanRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plan_execution::ComputePlanRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plan_execution::ComputePlanRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::plan_execution::ComputePlanRequest_<ContainerAllocator1> & lhs, const ::plan_execution::ComputePlanRequest_<ContainerAllocator2> & rhs)
{
  return lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::plan_execution::ComputePlanRequest_<ContainerAllocator1> & lhs, const ::plan_execution::ComputePlanRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace plan_execution

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::plan_execution::ComputePlanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plan_execution::ComputePlanRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plan_execution::ComputePlanRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plan_execution::ComputePlanRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plan_execution::ComputePlanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plan_execution::ComputePlanRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plan_execution::ComputePlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b55d8ef52d6fee225414e9d23b3ecc6";
  }

  static const char* value(const ::plan_execution::ComputePlanRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b55d8ef52d6fee2ULL;
  static const uint64_t static_value2 = 0x25414e9d23b3ecc6ULL;
};

template<class ContainerAllocator>
struct DataType< ::plan_execution::ComputePlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plan_execution/ComputePlanRequest";
  }

  static const char* value(const ::plan_execution::ComputePlanRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plan_execution::ComputePlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "AspRule[] goal\n"
"\n"
"================================================================================\n"
"MSG: plan_execution/AspRule\n"
"AspFluent[] head\n"
"AspFluent[] body\n"
"\n"
"================================================================================\n"
"MSG: plan_execution/AspFluent\n"
"string name\n"
"string[] variables\n"
"uint32 timeStep\n"
;
  }

  static const char* value(const ::plan_execution::ComputePlanRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plan_execution::ComputePlanRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ComputePlanRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plan_execution::ComputePlanRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plan_execution::ComputePlanRequest_<ContainerAllocator>& v)
  {
    s << indent << "goal[]" << std::endl;
    for (size_t i = 0; i < v.goal.size(); ++i)
    {
      s << indent << "  goal[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::plan_execution::AspRule_<ContainerAllocator> >::stream(s, indent + "    ", v.goal[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLAN_EXECUTION_MESSAGE_COMPUTEPLANREQUEST_H
