// Generated by gencpp from file plan_execution/CurrentStateQuery.msg
// DO NOT EDIT!


#ifndef PLAN_EXECUTION_MESSAGE_CURRENTSTATEQUERY_H
#define PLAN_EXECUTION_MESSAGE_CURRENTSTATEQUERY_H

#include <ros/service_traits.h>


#include <plan_execution/CurrentStateQueryRequest.h>
#include <plan_execution/CurrentStateQueryResponse.h>


namespace plan_execution
{

struct CurrentStateQuery
{

typedef CurrentStateQueryRequest Request;
typedef CurrentStateQueryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CurrentStateQuery
} // namespace plan_execution


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plan_execution::CurrentStateQuery > {
  static const char* value()
  {
    return "2cbc1d643059afa4b61504739724cdfc";
  }

  static const char* value(const ::plan_execution::CurrentStateQuery&) { return value(); }
};

template<>
struct DataType< ::plan_execution::CurrentStateQuery > {
  static const char* value()
  {
    return "plan_execution/CurrentStateQuery";
  }

  static const char* value(const ::plan_execution::CurrentStateQuery&) { return value(); }
};


// service_traits::MD5Sum< ::plan_execution::CurrentStateQueryRequest> should match
// service_traits::MD5Sum< ::plan_execution::CurrentStateQuery >
template<>
struct MD5Sum< ::plan_execution::CurrentStateQueryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::plan_execution::CurrentStateQuery >::value();
  }
  static const char* value(const ::plan_execution::CurrentStateQueryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::plan_execution::CurrentStateQueryRequest> should match
// service_traits::DataType< ::plan_execution::CurrentStateQuery >
template<>
struct DataType< ::plan_execution::CurrentStateQueryRequest>
{
  static const char* value()
  {
    return DataType< ::plan_execution::CurrentStateQuery >::value();
  }
  static const char* value(const ::plan_execution::CurrentStateQueryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plan_execution::CurrentStateQueryResponse> should match
// service_traits::MD5Sum< ::plan_execution::CurrentStateQuery >
template<>
struct MD5Sum< ::plan_execution::CurrentStateQueryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::plan_execution::CurrentStateQuery >::value();
  }
  static const char* value(const ::plan_execution::CurrentStateQueryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::plan_execution::CurrentStateQueryResponse> should match
// service_traits::DataType< ::plan_execution::CurrentStateQuery >
template<>
struct DataType< ::plan_execution::CurrentStateQueryResponse>
{
  static const char* value()
  {
    return DataType< ::plan_execution::CurrentStateQuery >::value();
  }
  static const char* value(const ::plan_execution::CurrentStateQueryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLAN_EXECUTION_MESSAGE_CURRENTSTATEQUERY_H
