// Generated by gencpp from file plan_execution/ExecuteSmachStateMachineFeedback.msg
// DO NOT EDIT!


#ifndef PLAN_EXECUTION_MESSAGE_EXECUTESMACHSTATEMACHINEFEEDBACK_H
#define PLAN_EXECUTION_MESSAGE_EXECUTESMACHSTATEMACHINEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace plan_execution
{
template <class ContainerAllocator>
struct ExecuteSmachStateMachineFeedback_
{
  typedef ExecuteSmachStateMachineFeedback_<ContainerAllocator> Type;

  ExecuteSmachStateMachineFeedback_()
    {
    }
  ExecuteSmachStateMachineFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::plan_execution::ExecuteSmachStateMachineFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plan_execution::ExecuteSmachStateMachineFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteSmachStateMachineFeedback_

typedef ::plan_execution::ExecuteSmachStateMachineFeedback_<std::allocator<void> > ExecuteSmachStateMachineFeedback;

typedef boost::shared_ptr< ::plan_execution::ExecuteSmachStateMachineFeedback > ExecuteSmachStateMachineFeedbackPtr;
typedef boost::shared_ptr< ::plan_execution::ExecuteSmachStateMachineFeedback const> ExecuteSmachStateMachineFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plan_execution::ExecuteSmachStateMachineFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plan_execution::ExecuteSmachStateMachineFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace plan_execution

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::plan_execution::ExecuteSmachStateMachineFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plan_execution::ExecuteSmachStateMachineFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plan_execution::ExecuteSmachStateMachineFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plan_execution::ExecuteSmachStateMachineFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plan_execution::ExecuteSmachStateMachineFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plan_execution::ExecuteSmachStateMachineFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plan_execution::ExecuteSmachStateMachineFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::plan_execution::ExecuteSmachStateMachineFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::plan_execution::ExecuteSmachStateMachineFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plan_execution/ExecuteSmachStateMachineFeedback";
  }

  static const char* value(const ::plan_execution::ExecuteSmachStateMachineFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plan_execution::ExecuteSmachStateMachineFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
;
  }

  static const char* value(const ::plan_execution::ExecuteSmachStateMachineFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plan_execution::ExecuteSmachStateMachineFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteSmachStateMachineFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plan_execution::ExecuteSmachStateMachineFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::plan_execution::ExecuteSmachStateMachineFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PLAN_EXECUTION_MESSAGE_EXECUTESMACHSTATEMACHINEFEEDBACK_H
