// Generated by gencpp from file plan_execution/GetHriMessage.msg
// DO NOT EDIT!


#ifndef PLAN_EXECUTION_MESSAGE_GETHRIMESSAGE_H
#define PLAN_EXECUTION_MESSAGE_GETHRIMESSAGE_H

#include <ros/service_traits.h>


#include <plan_execution/GetHriMessageRequest.h>
#include <plan_execution/GetHriMessageResponse.h>


namespace plan_execution
{

struct GetHriMessage
{

typedef GetHriMessageRequest Request;
typedef GetHriMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetHriMessage
} // namespace plan_execution


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plan_execution::GetHriMessage > {
  static const char* value()
  {
    return "09269fe575715249f3753f62218a600a";
  }

  static const char* value(const ::plan_execution::GetHriMessage&) { return value(); }
};

template<>
struct DataType< ::plan_execution::GetHriMessage > {
  static const char* value()
  {
    return "plan_execution/GetHriMessage";
  }

  static const char* value(const ::plan_execution::GetHriMessage&) { return value(); }
};


// service_traits::MD5Sum< ::plan_execution::GetHriMessageRequest> should match
// service_traits::MD5Sum< ::plan_execution::GetHriMessage >
template<>
struct MD5Sum< ::plan_execution::GetHriMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::plan_execution::GetHriMessage >::value();
  }
  static const char* value(const ::plan_execution::GetHriMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::plan_execution::GetHriMessageRequest> should match
// service_traits::DataType< ::plan_execution::GetHriMessage >
template<>
struct DataType< ::plan_execution::GetHriMessageRequest>
{
  static const char* value()
  {
    return DataType< ::plan_execution::GetHriMessage >::value();
  }
  static const char* value(const ::plan_execution::GetHriMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plan_execution::GetHriMessageResponse> should match
// service_traits::MD5Sum< ::plan_execution::GetHriMessage >
template<>
struct MD5Sum< ::plan_execution::GetHriMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::plan_execution::GetHriMessage >::value();
  }
  static const char* value(const ::plan_execution::GetHriMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::plan_execution::GetHriMessageResponse> should match
// service_traits::DataType< ::plan_execution::GetHriMessage >
template<>
struct DataType< ::plan_execution::GetHriMessageResponse>
{
  static const char* value()
  {
    return DataType< ::plan_execution::GetHriMessage >::value();
  }
  static const char* value(const ::plan_execution::GetHriMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLAN_EXECUTION_MESSAGE_GETHRIMESSAGE_H
