// Generated by gencpp from file bwi_moveit_utils/MoveitWaypoint.msg
// DO NOT EDIT!


#ifndef BWI_MOVEIT_UTILS_MESSAGE_MOVEITWAYPOINT_H
#define BWI_MOVEIT_UTILS_MESSAGE_MOVEITWAYPOINT_H

#include <ros/service_traits.h>


#include <bwi_moveit_utils/MoveitWaypointRequest.h>
#include <bwi_moveit_utils/MoveitWaypointResponse.h>


namespace bwi_moveit_utils
{

struct MoveitWaypoint
{

typedef MoveitWaypointRequest Request;
typedef MoveitWaypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveitWaypoint
} // namespace bwi_moveit_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bwi_moveit_utils::MoveitWaypoint > {
  static const char* value()
  {
    return "f8932f0bdb65419ee0fbaf236c79a04f";
  }

  static const char* value(const ::bwi_moveit_utils::MoveitWaypoint&) { return value(); }
};

template<>
struct DataType< ::bwi_moveit_utils::MoveitWaypoint > {
  static const char* value()
  {
    return "bwi_moveit_utils/MoveitWaypoint";
  }

  static const char* value(const ::bwi_moveit_utils::MoveitWaypoint&) { return value(); }
};


// service_traits::MD5Sum< ::bwi_moveit_utils::MoveitWaypointRequest> should match
// service_traits::MD5Sum< ::bwi_moveit_utils::MoveitWaypoint >
template<>
struct MD5Sum< ::bwi_moveit_utils::MoveitWaypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_moveit_utils::MoveitWaypoint >::value();
  }
  static const char* value(const ::bwi_moveit_utils::MoveitWaypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_moveit_utils::MoveitWaypointRequest> should match
// service_traits::DataType< ::bwi_moveit_utils::MoveitWaypoint >
template<>
struct DataType< ::bwi_moveit_utils::MoveitWaypointRequest>
{
  static const char* value()
  {
    return DataType< ::bwi_moveit_utils::MoveitWaypoint >::value();
  }
  static const char* value(const ::bwi_moveit_utils::MoveitWaypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bwi_moveit_utils::MoveitWaypointResponse> should match
// service_traits::MD5Sum< ::bwi_moveit_utils::MoveitWaypoint >
template<>
struct MD5Sum< ::bwi_moveit_utils::MoveitWaypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_moveit_utils::MoveitWaypoint >::value();
  }
  static const char* value(const ::bwi_moveit_utils::MoveitWaypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_moveit_utils::MoveitWaypointResponse> should match
// service_traits::DataType< ::bwi_moveit_utils::MoveitWaypoint >
template<>
struct DataType< ::bwi_moveit_utils::MoveitWaypointResponse>
{
  static const char* value()
  {
    return DataType< ::bwi_moveit_utils::MoveitWaypoint >::value();
  }
  static const char* value(const ::bwi_moveit_utils::MoveitWaypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BWI_MOVEIT_UTILS_MESSAGE_MOVEITWAYPOINT_H
