// Generated by gencpp from file bwi_planning_common/PlannerAtom.msg
// DO NOT EDIT!


#ifndef BWI_PLANNING_COMMON_MESSAGE_PLANNERATOM_H
#define BWI_PLANNING_COMMON_MESSAGE_PLANNERATOM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bwi_planning_common
{
template <class ContainerAllocator>
struct PlannerAtom_
{
  typedef PlannerAtom_<ContainerAllocator> Type;

  PlannerAtom_()
    : name()
    , value()  {
    }
  PlannerAtom_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , value(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::bwi_planning_common::PlannerAtom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bwi_planning_common::PlannerAtom_<ContainerAllocator> const> ConstPtr;

}; // struct PlannerAtom_

typedef ::bwi_planning_common::PlannerAtom_<std::allocator<void> > PlannerAtom;

typedef boost::shared_ptr< ::bwi_planning_common::PlannerAtom > PlannerAtomPtr;
typedef boost::shared_ptr< ::bwi_planning_common::PlannerAtom const> PlannerAtomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bwi_planning_common::PlannerAtom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bwi_planning_common::PlannerAtom_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bwi_planning_common::PlannerAtom_<ContainerAllocator1> & lhs, const ::bwi_planning_common::PlannerAtom_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bwi_planning_common::PlannerAtom_<ContainerAllocator1> & lhs, const ::bwi_planning_common::PlannerAtom_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bwi_planning_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::bwi_planning_common::PlannerAtom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bwi_planning_common::PlannerAtom_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_planning_common::PlannerAtom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_planning_common::PlannerAtom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_planning_common::PlannerAtom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_planning_common::PlannerAtom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bwi_planning_common::PlannerAtom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a20c942da620dbf29654f430aa251492";
  }

  static const char* value(const ::bwi_planning_common::PlannerAtom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa20c942da620dbf2ULL;
  static const uint64_t static_value2 = 0x9654f430aa251492ULL;
};

template<class ContainerAllocator>
struct DataType< ::bwi_planning_common::PlannerAtom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bwi_planning_common/PlannerAtom";
  }

  static const char* value(const ::bwi_planning_common::PlannerAtom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bwi_planning_common::PlannerAtom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"string[] value\n"
;
  }

  static const char* value(const ::bwi_planning_common::PlannerAtom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bwi_planning_common::PlannerAtom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlannerAtom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bwi_planning_common::PlannerAtom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bwi_planning_common::PlannerAtom_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "value[]" << std::endl;
    for (size_t i = 0; i < v.value.size(); ++i)
    {
      s << indent << "  value[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BWI_PLANNING_COMMON_MESSAGE_PLANNERATOM_H
