// Generated by gencpp from file bwi_planning_common/PlannerInterfaceRequest.msg
// DO NOT EDIT!


#ifndef BWI_PLANNING_COMMON_MESSAGE_PLANNERINTERFACEREQUEST_H
#define BWI_PLANNING_COMMON_MESSAGE_PLANNERINTERFACEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <bwi_planning_common/PlannerAtom.h>

namespace bwi_planning_common
{
template <class ContainerAllocator>
struct PlannerInterfaceRequest_
{
  typedef PlannerInterfaceRequest_<ContainerAllocator> Type;

  PlannerInterfaceRequest_()
    : command()  {
    }
  PlannerInterfaceRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef  ::bwi_planning_common::PlannerAtom_<ContainerAllocator>  _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlannerInterfaceRequest_

typedef ::bwi_planning_common::PlannerInterfaceRequest_<std::allocator<void> > PlannerInterfaceRequest;

typedef boost::shared_ptr< ::bwi_planning_common::PlannerInterfaceRequest > PlannerInterfaceRequestPtr;
typedef boost::shared_ptr< ::bwi_planning_common::PlannerInterfaceRequest const> PlannerInterfaceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator1> & lhs, const ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator1> & lhs, const ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bwi_planning_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b44d18631c1272d8bcb3e1f37b50d61";
  }

  static const char* value(const ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b44d18631c1272dULL;
  static const uint64_t static_value2 = 0x8bcb3e1f37b50d61ULL;
};

template<class ContainerAllocator>
struct DataType< ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bwi_planning_common/PlannerInterfaceRequest";
  }

  static const char* value(const ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PlannerAtom command\n"
"\n"
"================================================================================\n"
"MSG: bwi_planning_common/PlannerAtom\n"
"string name\n"
"string[] value\n"
;
  }

  static const char* value(const ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlannerInterfaceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bwi_planning_common::PlannerInterfaceRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    s << std::endl;
    Printer< ::bwi_planning_common::PlannerAtom_<ContainerAllocator> >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BWI_PLANNING_COMMON_MESSAGE_PLANNERINTERFACEREQUEST_H
