// Generated by gencpp from file bwi_virtour/LeaveTourResponse.msg
// DO NOT EDIT!


#ifndef BWI_VIRTOUR_MESSAGE_LEAVETOURRESPONSE_H
#define BWI_VIRTOUR_MESSAGE_LEAVETOURRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bwi_virtour
{
template <class ContainerAllocator>
struct LeaveTourResponse_
{
  typedef LeaveTourResponse_<ContainerAllocator> Type;

  LeaveTourResponse_()
    : result(0)  {
    }
  LeaveTourResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::bwi_virtour::LeaveTourResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bwi_virtour::LeaveTourResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LeaveTourResponse_

typedef ::bwi_virtour::LeaveTourResponse_<std::allocator<void> > LeaveTourResponse;

typedef boost::shared_ptr< ::bwi_virtour::LeaveTourResponse > LeaveTourResponsePtr;
typedef boost::shared_ptr< ::bwi_virtour::LeaveTourResponse const> LeaveTourResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bwi_virtour::LeaveTourResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bwi_virtour::LeaveTourResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bwi_virtour::LeaveTourResponse_<ContainerAllocator1> & lhs, const ::bwi_virtour::LeaveTourResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bwi_virtour::LeaveTourResponse_<ContainerAllocator1> & lhs, const ::bwi_virtour::LeaveTourResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bwi_virtour

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::bwi_virtour::LeaveTourResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bwi_virtour::LeaveTourResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_virtour::LeaveTourResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_virtour::LeaveTourResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_virtour::LeaveTourResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_virtour::LeaveTourResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bwi_virtour::LeaveTourResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::bwi_virtour::LeaveTourResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::bwi_virtour::LeaveTourResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bwi_virtour/LeaveTourResponse";
  }

  static const char* value(const ::bwi_virtour::LeaveTourResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bwi_virtour::LeaveTourResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n"
"\n"
;
  }

  static const char* value(const ::bwi_virtour::LeaveTourResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bwi_virtour::LeaveTourResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LeaveTourResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bwi_virtour::LeaveTourResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bwi_virtour::LeaveTourResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BWI_VIRTOUR_MESSAGE_LEAVETOURRESPONSE_H
