# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from segway_msgs/Propulsion.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Propulsion(genpy.Message):
  _md5sum = "8db8f550407de4bfaf53927720c28e50"
  _type = "segway_msgs/Propulsion"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
float32 min_propulsion_battery_soc
float32[] mcu_battery_soc
float32[] mcu_battery_temp_degC
float32[] mcu_inst_power_W
float32[] mcu_total_energy_Wh
float32[] motor_current_A0pk
float32 max_motor_current_A0pk
float32[] motor_current_limit_A0pk
float32 min_motor_current_limit_A0pk



================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','min_propulsion_battery_soc','mcu_battery_soc','mcu_battery_temp_degC','mcu_inst_power_W','mcu_total_energy_Wh','motor_current_A0pk','max_motor_current_A0pk','motor_current_limit_A0pk','min_motor_current_limit_A0pk']
  _slot_types = ['std_msgs/Header','float32','float32[]','float32[]','float32[]','float32[]','float32[]','float32','float32[]','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,min_propulsion_battery_soc,mcu_battery_soc,mcu_battery_temp_degC,mcu_inst_power_W,mcu_total_energy_Wh,motor_current_A0pk,max_motor_current_A0pk,motor_current_limit_A0pk,min_motor_current_limit_A0pk

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Propulsion, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.min_propulsion_battery_soc is None:
        self.min_propulsion_battery_soc = 0.
      if self.mcu_battery_soc is None:
        self.mcu_battery_soc = []
      if self.mcu_battery_temp_degC is None:
        self.mcu_battery_temp_degC = []
      if self.mcu_inst_power_W is None:
        self.mcu_inst_power_W = []
      if self.mcu_total_energy_Wh is None:
        self.mcu_total_energy_Wh = []
      if self.motor_current_A0pk is None:
        self.motor_current_A0pk = []
      if self.max_motor_current_A0pk is None:
        self.max_motor_current_A0pk = 0.
      if self.motor_current_limit_A0pk is None:
        self.motor_current_limit_A0pk = []
      if self.min_motor_current_limit_A0pk is None:
        self.min_motor_current_limit_A0pk = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.min_propulsion_battery_soc = 0.
      self.mcu_battery_soc = []
      self.mcu_battery_temp_degC = []
      self.mcu_inst_power_W = []
      self.mcu_total_energy_Wh = []
      self.motor_current_A0pk = []
      self.max_motor_current_A0pk = 0.
      self.motor_current_limit_A0pk = []
      self.min_motor_current_limit_A0pk = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.min_propulsion_battery_soc
      buff.write(_get_struct_f().pack(_x))
      length = len(self.mcu_battery_soc)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.mcu_battery_soc))
      length = len(self.mcu_battery_temp_degC)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.mcu_battery_temp_degC))
      length = len(self.mcu_inst_power_W)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.mcu_inst_power_W))
      length = len(self.mcu_total_energy_Wh)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.mcu_total_energy_Wh))
      length = len(self.motor_current_A0pk)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.motor_current_A0pk))
      _x = self.max_motor_current_A0pk
      buff.write(_get_struct_f().pack(_x))
      length = len(self.motor_current_limit_A0pk)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.motor_current_limit_A0pk))
      _x = self.min_motor_current_limit_A0pk
      buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.min_propulsion_battery_soc,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.mcu_battery_soc = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.mcu_battery_temp_degC = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.mcu_inst_power_W = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.mcu_total_energy_Wh = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.motor_current_A0pk = s.unpack(str[start:end])
      start = end
      end += 4
      (self.max_motor_current_A0pk,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.motor_current_limit_A0pk = s.unpack(str[start:end])
      start = end
      end += 4
      (self.min_motor_current_limit_A0pk,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.min_propulsion_battery_soc
      buff.write(_get_struct_f().pack(_x))
      length = len(self.mcu_battery_soc)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.mcu_battery_soc.tostring())
      length = len(self.mcu_battery_temp_degC)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.mcu_battery_temp_degC.tostring())
      length = len(self.mcu_inst_power_W)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.mcu_inst_power_W.tostring())
      length = len(self.mcu_total_energy_Wh)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.mcu_total_energy_Wh.tostring())
      length = len(self.motor_current_A0pk)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.motor_current_A0pk.tostring())
      _x = self.max_motor_current_A0pk
      buff.write(_get_struct_f().pack(_x))
      length = len(self.motor_current_limit_A0pk)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.motor_current_limit_A0pk.tostring())
      _x = self.min_motor_current_limit_A0pk
      buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.min_propulsion_battery_soc,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.mcu_battery_soc = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.mcu_battery_temp_degC = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.mcu_inst_power_W = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.mcu_total_energy_Wh = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.motor_current_A0pk = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (self.max_motor_current_A0pk,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.motor_current_limit_A0pk = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (self.min_motor_current_limit_A0pk,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
