// Generated by gencpp from file bwi_perception/FeatureExtraction.msg
// DO NOT EDIT!


#ifndef BWI_PERCEPTION_MESSAGE_FEATUREEXTRACTION_H
#define BWI_PERCEPTION_MESSAGE_FEATUREEXTRACTION_H

#include <ros/service_traits.h>


#include <bwi_perception/FeatureExtractionRequest.h>
#include <bwi_perception/FeatureExtractionResponse.h>


namespace bwi_perception
{

struct FeatureExtraction
{

typedef FeatureExtractionRequest Request;
typedef FeatureExtractionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FeatureExtraction
} // namespace bwi_perception


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bwi_perception::FeatureExtraction > {
  static const char* value()
  {
    return "d1e05f2e0627a4123131d2576998f66b";
  }

  static const char* value(const ::bwi_perception::FeatureExtraction&) { return value(); }
};

template<>
struct DataType< ::bwi_perception::FeatureExtraction > {
  static const char* value()
  {
    return "bwi_perception/FeatureExtraction";
  }

  static const char* value(const ::bwi_perception::FeatureExtraction&) { return value(); }
};


// service_traits::MD5Sum< ::bwi_perception::FeatureExtractionRequest> should match
// service_traits::MD5Sum< ::bwi_perception::FeatureExtraction >
template<>
struct MD5Sum< ::bwi_perception::FeatureExtractionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_perception::FeatureExtraction >::value();
  }
  static const char* value(const ::bwi_perception::FeatureExtractionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_perception::FeatureExtractionRequest> should match
// service_traits::DataType< ::bwi_perception::FeatureExtraction >
template<>
struct DataType< ::bwi_perception::FeatureExtractionRequest>
{
  static const char* value()
  {
    return DataType< ::bwi_perception::FeatureExtraction >::value();
  }
  static const char* value(const ::bwi_perception::FeatureExtractionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bwi_perception::FeatureExtractionResponse> should match
// service_traits::MD5Sum< ::bwi_perception::FeatureExtraction >
template<>
struct MD5Sum< ::bwi_perception::FeatureExtractionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_perception::FeatureExtraction >::value();
  }
  static const char* value(const ::bwi_perception::FeatureExtractionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_perception::FeatureExtractionResponse> should match
// service_traits::DataType< ::bwi_perception::FeatureExtraction >
template<>
struct DataType< ::bwi_perception::FeatureExtractionResponse>
{
  static const char* value()
  {
    return DataType< ::bwi_perception::FeatureExtraction >::value();
  }
  static const char* value(const ::bwi_perception::FeatureExtractionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BWI_PERCEPTION_MESSAGE_FEATUREEXTRACTION_H
