// Generated by gencpp from file bwi_perception/PerceiveTabletopScene.msg
// DO NOT EDIT!


#ifndef BWI_PERCEPTION_MESSAGE_PERCEIVETABLETOPSCENE_H
#define BWI_PERCEPTION_MESSAGE_PERCEIVETABLETOPSCENE_H

#include <ros/service_traits.h>


#include <bwi_perception/PerceiveTabletopSceneRequest.h>
#include <bwi_perception/PerceiveTabletopSceneResponse.h>


namespace bwi_perception
{

struct PerceiveTabletopScene
{

typedef PerceiveTabletopSceneRequest Request;
typedef PerceiveTabletopSceneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PerceiveTabletopScene
} // namespace bwi_perception


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bwi_perception::PerceiveTabletopScene > {
  static const char* value()
  {
    return "162567af3b2a6902ed12ffdefcc8587f";
  }

  static const char* value(const ::bwi_perception::PerceiveTabletopScene&) { return value(); }
};

template<>
struct DataType< ::bwi_perception::PerceiveTabletopScene > {
  static const char* value()
  {
    return "bwi_perception/PerceiveTabletopScene";
  }

  static const char* value(const ::bwi_perception::PerceiveTabletopScene&) { return value(); }
};


// service_traits::MD5Sum< ::bwi_perception::PerceiveTabletopSceneRequest> should match
// service_traits::MD5Sum< ::bwi_perception::PerceiveTabletopScene >
template<>
struct MD5Sum< ::bwi_perception::PerceiveTabletopSceneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_perception::PerceiveTabletopScene >::value();
  }
  static const char* value(const ::bwi_perception::PerceiveTabletopSceneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_perception::PerceiveTabletopSceneRequest> should match
// service_traits::DataType< ::bwi_perception::PerceiveTabletopScene >
template<>
struct DataType< ::bwi_perception::PerceiveTabletopSceneRequest>
{
  static const char* value()
  {
    return DataType< ::bwi_perception::PerceiveTabletopScene >::value();
  }
  static const char* value(const ::bwi_perception::PerceiveTabletopSceneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bwi_perception::PerceiveTabletopSceneResponse> should match
// service_traits::MD5Sum< ::bwi_perception::PerceiveTabletopScene >
template<>
struct MD5Sum< ::bwi_perception::PerceiveTabletopSceneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_perception::PerceiveTabletopScene >::value();
  }
  static const char* value(const ::bwi_perception::PerceiveTabletopSceneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_perception::PerceiveTabletopSceneResponse> should match
// service_traits::DataType< ::bwi_perception::PerceiveTabletopScene >
template<>
struct DataType< ::bwi_perception::PerceiveTabletopSceneResponse>
{
  static const char* value()
  {
    return DataType< ::bwi_perception::PerceiveTabletopScene >::value();
  }
  static const char* value(const ::bwi_perception::PerceiveTabletopSceneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BWI_PERCEPTION_MESSAGE_PERCEIVETABLETOPSCENE_H
