// Generated by gencpp from file bwi_perception/PerceiveLargestHorizontalPlane.msg
// DO NOT EDIT!


#ifndef BWI_PERCEPTION_MESSAGE_PERCEIVELARGESTHORIZONTALPLANE_H
#define BWI_PERCEPTION_MESSAGE_PERCEIVELARGESTHORIZONTALPLANE_H

#include <ros/service_traits.h>


#include <bwi_perception/PerceiveLargestHorizontalPlaneRequest.h>
#include <bwi_perception/PerceiveLargestHorizontalPlaneResponse.h>


namespace bwi_perception
{

struct PerceiveLargestHorizontalPlane
{

typedef PerceiveLargestHorizontalPlaneRequest Request;
typedef PerceiveLargestHorizontalPlaneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PerceiveLargestHorizontalPlane
} // namespace bwi_perception


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bwi_perception::PerceiveLargestHorizontalPlane > {
  static const char* value()
  {
    return "34fffc23b5e8ba50f79d3b901bb1af8e";
  }

  static const char* value(const ::bwi_perception::PerceiveLargestHorizontalPlane&) { return value(); }
};

template<>
struct DataType< ::bwi_perception::PerceiveLargestHorizontalPlane > {
  static const char* value()
  {
    return "bwi_perception/PerceiveLargestHorizontalPlane";
  }

  static const char* value(const ::bwi_perception::PerceiveLargestHorizontalPlane&) { return value(); }
};


// service_traits::MD5Sum< ::bwi_perception::PerceiveLargestHorizontalPlaneRequest> should match
// service_traits::MD5Sum< ::bwi_perception::PerceiveLargestHorizontalPlane >
template<>
struct MD5Sum< ::bwi_perception::PerceiveLargestHorizontalPlaneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_perception::PerceiveLargestHorizontalPlane >::value();
  }
  static const char* value(const ::bwi_perception::PerceiveLargestHorizontalPlaneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_perception::PerceiveLargestHorizontalPlaneRequest> should match
// service_traits::DataType< ::bwi_perception::PerceiveLargestHorizontalPlane >
template<>
struct DataType< ::bwi_perception::PerceiveLargestHorizontalPlaneRequest>
{
  static const char* value()
  {
    return DataType< ::bwi_perception::PerceiveLargestHorizontalPlane >::value();
  }
  static const char* value(const ::bwi_perception::PerceiveLargestHorizontalPlaneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bwi_perception::PerceiveLargestHorizontalPlaneResponse> should match
// service_traits::MD5Sum< ::bwi_perception::PerceiveLargestHorizontalPlane >
template<>
struct MD5Sum< ::bwi_perception::PerceiveLargestHorizontalPlaneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_perception::PerceiveLargestHorizontalPlane >::value();
  }
  static const char* value(const ::bwi_perception::PerceiveLargestHorizontalPlaneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_perception::PerceiveLargestHorizontalPlaneResponse> should match
// service_traits::DataType< ::bwi_perception::PerceiveLargestHorizontalPlane >
template<>
struct DataType< ::bwi_perception::PerceiveLargestHorizontalPlaneResponse>
{
  static const char* value()
  {
    return DataType< ::bwi_perception::PerceiveLargestHorizontalPlane >::value();
  }
  static const char* value(const ::bwi_perception::PerceiveLargestHorizontalPlaneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BWI_PERCEPTION_MESSAGE_PERCEIVELARGESTHORIZONTALPLANE_H
