// Generated by gencpp from file bwi_perception/ProcessVision.msg
// DO NOT EDIT!


#ifndef BWI_PERCEPTION_MESSAGE_PROCESSVISION_H
#define BWI_PERCEPTION_MESSAGE_PROCESSVISION_H

#include <ros/service_traits.h>


#include <bwi_perception/ProcessVisionRequest.h>
#include <bwi_perception/ProcessVisionResponse.h>


namespace bwi_perception
{

struct ProcessVision
{

typedef ProcessVisionRequest Request;
typedef ProcessVisionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ProcessVision
} // namespace bwi_perception


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bwi_perception::ProcessVision > {
  static const char* value()
  {
    return "6e09057bca6c469f3261816784f3e445";
  }

  static const char* value(const ::bwi_perception::ProcessVision&) { return value(); }
};

template<>
struct DataType< ::bwi_perception::ProcessVision > {
  static const char* value()
  {
    return "bwi_perception/ProcessVision";
  }

  static const char* value(const ::bwi_perception::ProcessVision&) { return value(); }
};


// service_traits::MD5Sum< ::bwi_perception::ProcessVisionRequest> should match
// service_traits::MD5Sum< ::bwi_perception::ProcessVision >
template<>
struct MD5Sum< ::bwi_perception::ProcessVisionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_perception::ProcessVision >::value();
  }
  static const char* value(const ::bwi_perception::ProcessVisionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_perception::ProcessVisionRequest> should match
// service_traits::DataType< ::bwi_perception::ProcessVision >
template<>
struct DataType< ::bwi_perception::ProcessVisionRequest>
{
  static const char* value()
  {
    return DataType< ::bwi_perception::ProcessVision >::value();
  }
  static const char* value(const ::bwi_perception::ProcessVisionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bwi_perception::ProcessVisionResponse> should match
// service_traits::MD5Sum< ::bwi_perception::ProcessVision >
template<>
struct MD5Sum< ::bwi_perception::ProcessVisionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_perception::ProcessVision >::value();
  }
  static const char* value(const ::bwi_perception::ProcessVisionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_perception::ProcessVisionResponse> should match
// service_traits::DataType< ::bwi_perception::ProcessVision >
template<>
struct DataType< ::bwi_perception::ProcessVisionResponse>
{
  static const char* value()
  {
    return DataType< ::bwi_perception::ProcessVision >::value();
  }
  static const char* value(const ::bwi_perception::ProcessVisionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BWI_PERCEPTION_MESSAGE_PROCESSVISION_H
