// Generated by gencpp from file bwi_perception/SetObstaclesResponse.msg
// DO NOT EDIT!


#ifndef BWI_PERCEPTION_MESSAGE_SETOBSTACLESRESPONSE_H
#define BWI_PERCEPTION_MESSAGE_SETOBSTACLESRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bwi_perception
{
template <class ContainerAllocator>
struct SetObstaclesResponse_
{
  typedef SetObstaclesResponse_<ContainerAllocator> Type;

  SetObstaclesResponse_()
    : response(false)  {
    }
  SetObstaclesResponse_(const ContainerAllocator& _alloc)
    : response(false)  {
  (void)_alloc;
    }



   typedef uint8_t _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::bwi_perception::SetObstaclesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bwi_perception::SetObstaclesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetObstaclesResponse_

typedef ::bwi_perception::SetObstaclesResponse_<std::allocator<void> > SetObstaclesResponse;

typedef boost::shared_ptr< ::bwi_perception::SetObstaclesResponse > SetObstaclesResponsePtr;
typedef boost::shared_ptr< ::bwi_perception::SetObstaclesResponse const> SetObstaclesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bwi_perception::SetObstaclesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bwi_perception::SetObstaclesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bwi_perception::SetObstaclesResponse_<ContainerAllocator1> & lhs, const ::bwi_perception::SetObstaclesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bwi_perception::SetObstaclesResponse_<ContainerAllocator1> & lhs, const ::bwi_perception::SetObstaclesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bwi_perception

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::bwi_perception::SetObstaclesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bwi_perception::SetObstaclesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_perception::SetObstaclesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_perception::SetObstaclesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_perception::SetObstaclesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_perception::SetObstaclesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bwi_perception::SetObstaclesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "003b81baa95ab323fc1ddf3c7d0bee81";
  }

  static const char* value(const ::bwi_perception::SetObstaclesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x003b81baa95ab323ULL;
  static const uint64_t static_value2 = 0xfc1ddf3c7d0bee81ULL;
};

template<class ContainerAllocator>
struct DataType< ::bwi_perception::SetObstaclesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bwi_perception/SetObstaclesResponse";
  }

  static const char* value(const ::bwi_perception::SetObstaclesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bwi_perception::SetObstaclesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool response\n"
"\n"
;
  }

  static const char* value(const ::bwi_perception::SetObstaclesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bwi_perception::SetObstaclesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetObstaclesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bwi_perception::SetObstaclesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bwi_perception::SetObstaclesResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BWI_PERCEPTION_MESSAGE_SETOBSTACLESRESPONSE_H
