; Auto-generated. Do not edit!


(cl:in-package bwi_msgs-msg)


;//! \htmlinclude LogicalNavGoal.msg.html

(cl:defclass <LogicalNavGoal> (roslisp-msg-protocol:ros-message)
  ((command
    :reader command
    :initarg :command
    :type bwi_planning_common-msg:PlannerAtom
    :initform (cl:make-instance 'bwi_planning_common-msg:PlannerAtom)))
)

(cl:defclass LogicalNavGoal (<LogicalNavGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LogicalNavGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LogicalNavGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name bwi_msgs-msg:<LogicalNavGoal> is deprecated: use bwi_msgs-msg:LogicalNavGoal instead.")))

(cl:ensure-generic-function 'command-val :lambda-list '(m))
(cl:defmethod command-val ((m <LogicalNavGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader bwi_msgs-msg:command-val is deprecated.  Use bwi_msgs-msg:command instead.")
  (command m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LogicalNavGoal>) ostream)
  "Serializes a message object of type '<LogicalNavGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'command) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LogicalNavGoal>) istream)
  "Deserializes a message object of type '<LogicalNavGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'command) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LogicalNavGoal>)))
  "Returns string type for a message object of type '<LogicalNavGoal>"
  "bwi_msgs/LogicalNavGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LogicalNavGoal)))
  "Returns string type for a message object of type 'LogicalNavGoal"
  "bwi_msgs/LogicalNavGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LogicalNavGoal>)))
  "Returns md5sum for a message object of type '<LogicalNavGoal>"
  "3b44d18631c1272d8bcb3e1f37b50d61")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LogicalNavGoal)))
  "Returns md5sum for a message object of type 'LogicalNavGoal"
  "3b44d18631c1272d8bcb3e1f37b50d61")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LogicalNavGoal>)))
  "Returns full string definition for message of type '<LogicalNavGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bwi_planning_common/PlannerAtom command~%~%================================================================================~%MSG: bwi_planning_common/PlannerAtom~%string name~%string[] value~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LogicalNavGoal)))
  "Returns full string definition for message of type 'LogicalNavGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bwi_planning_common/PlannerAtom command~%~%================================================================================~%MSG: bwi_planning_common/PlannerAtom~%string name~%string[] value~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LogicalNavGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'command))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LogicalNavGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'LogicalNavGoal
    (cl:cons ':command (command msg))
))
