; Auto-generated. Do not edit!


(cl:in-package bwi_msgs-msg)


;//! \htmlinclude LogicalNavFeedback.msg.html

(cl:defclass <LogicalNavFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass LogicalNavFeedback (<LogicalNavFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LogicalNavFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LogicalNavFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name bwi_msgs-msg:<LogicalNavFeedback> is deprecated: use bwi_msgs-msg:LogicalNavFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LogicalNavFeedback>) ostream)
  "Serializes a message object of type '<LogicalNavFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LogicalNavFeedback>) istream)
  "Deserializes a message object of type '<LogicalNavFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LogicalNavFeedback>)))
  "Returns string type for a message object of type '<LogicalNavFeedback>"
  "bwi_msgs/LogicalNavFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LogicalNavFeedback)))
  "Returns string type for a message object of type 'LogicalNavFeedback"
  "bwi_msgs/LogicalNavFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LogicalNavFeedback>)))
  "Returns md5sum for a message object of type '<LogicalNavFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LogicalNavFeedback)))
  "Returns md5sum for a message object of type 'LogicalNavFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LogicalNavFeedback>)))
  "Returns full string definition for message of type '<LogicalNavFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LogicalNavFeedback)))
  "Returns full string definition for message of type 'LogicalNavFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LogicalNavFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LogicalNavFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LogicalNavFeedback
))
